name: Gradle CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: reattach HEAD to Head Ref
        run: git checkout "$(echo ${{ github.head_ref }} | sed -E 's|refs/[a-zA-Z]+/||')"
        if: github.head_ref != ''
      - name: reattach HEAD to Ref
        run: git checkout "$(echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||')"
        if: github.head_ref == ''
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Build with Gradle
        run: chmod +x ./gradlew && ./gradlew clean build
      - name: Upload to Discord
        if: github.ref == 'refs/heads/master'
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: mythicdrops/build/distributions/MythicDrops*.zip
